[tool.poetry]
name = "mabby"
version = "0.1.0"
description = "A multi-armed bandit (MAB) simulation library"
authors = ["Ethan Wu <ew2664@columbia.edu>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.0.4"
black = "^23.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
