[tool.poetry]
name = "mabby"
version = "0.1.0"
description = "A multi-armed bandit (MAB) simulation library"
authors = ["Ethan Wu <ew2664@columbia.edu>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.24.2"
matplotlib = "^3.7.0"


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.0.4"
black = "^23.1.0"
mdformat = "^0.7.16"
mdformat-gfm = "^0.3.5"
mdformat-black = "^0.1.1"
mdformat-frontmatter = "^2.0.1"
mdformat-footnote = "^0.1.1"
mypy = "^1.0.1"
ruff = "^0.0.252"
pytest = "^7.2.1"
pytest-cov = "^4.0.0"
pytest-mock = "^3.10.0"

[tool.isort]
profile = "black"

[tool.mypy]
strict = true
warn_return_any = false

[[tool.mypy.overrides]]
module = "matplotlib.*"
ignore_missing_imports = true

[tool.ruff]
target-version = "py39"
select = ["E", "F", "I", "UP", "B", "Q", "SIM", "NPY", "RUF"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
